version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    resource_class: medium
    working_directory: ~/repo
    environment:
      GRAALVM_HOME: /home/circleci/repo/.graalvm
    steps:

      - checkout

      - run:
          name: Install GraalVM
          command: curl https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java11-linux-amd64-21.3.0.tar.gz -O -J -L && tar xfz graalvm-ce-java11-linux-amd64-21.3.0.tar.gz && mv graalvm-ce-java11-21.3.0 .graalvm && rm graalvm-ce-java11-linux-amd64-21.3.0.tar.gz

      - run:
          name: Install native-image
          command: $GRAALVM_HOME/bin/gu install native-image

      - run:
          name: Build (Native)
          command: ./mvnw clean package -Pnative -DskipTests -Dmaven.test.skip=true
          no_output_timeout: 30m

      - run:
          name: DockerHUB login
          command: echo ${DOCKER_PASS} | docker login --username ${DOCKER_USER} --password-stdin

      - run:
          name: Build Docker Image
          command: docker build -f ./src/main/docker/Dockerfile.native -t hablijack/eilkurier-backend:latest .

      - run:
          name: Push to DockerHUB
          command: docker push hablijack/eilkurier-backend:latest
