version: 2
jobs:
  build:
    machine: true
    resource_class: medium
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx6400m
      GRAALVM_HOME: /home/circleci/repo/.graalvm
    steps:
    
      - checkout

      - run:
          name: Install GraalVM
          command: curl https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.6/graalvm-ce-java11-linux-amd64-19.3.6.tar.gz -O -J -L && tar xfz graalvm-ce-java11-linux-amd64-19.3.6.tar.gz && mv graalvm-ce-java11-19.3.6 .graalvm && rm graalvm-ce-java11-linux-amd64-19.3.6.tar.gz
          
      - run:
          name: Install native-image
          command: $GRAALVM_HOME/bin/gu install native-image

      - run:
          name: Build (Native)
          command: ./mvnw clean package -Pnative -DskipTests -Dmaven.test.skip=true
          no_output_timeout: 30m
