version: 2

jobs:
  qualitygate:
    machine:
      image: ubuntu-2004:202008-01
    resource_class: medium
    steps:
      - checkout
      - run: ./mvnw clean compile spotbugs:check
      - run: ./mvnw clean compile pmd:check
      - run: ./mvnw clean compile checkstyle:check

  build:
    machine:
      image: ubuntu-2004:202008-01
    resource_class: medium
    working_directory: ~/repo
    environment:
      GRAALVM_HOME: /home/circleci/repo/.graalvm
    steps:
      - checkout
      - run: curl https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java11-linux-amd64-21.3.0.tar.gz -O -J -L && tar xfz graalvm-ce-java11-linux-amd64-21.3.0.tar.gz && mv graalvm-ce-java11-21.3.0 .graalvm && rm graalvm-ce-java11-linux-amd64-21.3.0.tar.gz
      - run: $GRAALVM_HOME/bin/gu install native-image
      - run: 
          command: ./mvnw clean package -Pnative -DskipTests -Dmaven.test.skip=true
          no_output_timeout: 30m
      - run: docker build -f ./src/main/docker/Dockerfile.native .
      - heroku/install
      - run: heroku container:login
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      - qualitygate
      - build